# Generated by Django 2.0.3 on 2018-04-26 18:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180426_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='课程详情'),
        ),
    ]
